spring:
  h2:
    console:
      enabled: true
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb
      username: sa
      password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true
    open-in-view: false
  datasource:
    generate-unique-name: false
  redis:
    port: 6379
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh

jwt:
  access-token-expire-time: 1800
  refresh-token-expire-time: 604800
  secret: f26326bb0fcaf211bf1c1965b23d63b46ecb111b3998d354986faae8235723613837fa62f484b71d29746d70dda0014b1f4cc6fcb46035b8add06c482774b096
