spring:
  application:
    name: battleq-api
  cloud:
    config:
      uri: http://www.gossing-server.com:8888
  config:
    import: 'configserver:'
  datasource:
    driver-class-name:
    url:
    username:
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      format_sql: true
    open-in-view: false
  redis:
    host: host
    port: 6379
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh

jwt:
  access-token-expire-time: 1800
  refresh-token-expire-time: 604800
  secret: secret

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}